'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Check, ChevronDown, CirclePlay, Clock3, Headphones, LockKeyhole, Menu, Moon, Pause, Play, Sparkles, Star, Volume2, X } from 'lucide-react'

type Meditation = { day: number; title: string; description: string; stage: string; audio: string }

const meditationData: Meditation[] = [
  ['Despertar de la luz interior','Un primer encuentro amable con tu presencia.','Despertar'],['Volver al momento presente','Ancla tu atención en este instante.','Despertar'],['Respirar con conciencia','Descubre la calma que vive en tu respiración.','Despertar'],['Escuchar el silencio','Haz espacio para escuchar lo esencial.','Despertar'],['Habitar tu cuerpo','Regresa a las sensaciones de tu cuerpo.','Despertar'],['Reconocer tu propia luz','Observa tus cualidades con ternura.','Despertar'],['Agradecer este comienzo','Celebra el regalo de haber comenzado.','Despertar'],['Soltar las tensiones','Permite que tu cuerpo descanse.','Liberar'],['Dejar ir lo que pesa','Suelta suavemente aquello que ya cumplió su ciclo.','Liberar'],['Crear espacio interior','Abre un lugar nuevo dentro de ti.','Liberar'],['Aceptar el presente','Recibe este momento tal como es.','Liberar'],['Abrazar tus emociones','Mira lo que sientes con compasión.','Liberar'],['Descansar sin culpa','El descanso también es parte del camino.','Liberar'],['Renovar tu serenidad','Vuelve a elegir la quietud.','Liberar'],['Cultivar la confianza','Confía en tu capacidad de avanzar.','Fortalecer'],['Reconocer tu valor','Recuerda que tu presencia importa.','Fortalecer'],['Escuchar tu intuición','Presta atención a esa voz interna.','Fortalecer'],['Elegir pensamientos amables','Cambia la exigencia por amabilidad.','Fortalecer'],['Fortalecer tu paz','Protege el espacio sereno que has creado.','Fortalecer'],['Conectar con tu propósito','Acércate a aquello que da sentido a tus días.','Fortalecer'],['Honrar tu camino','Reconoce todo lo que ya has recorrido.','Fortalecer'],['Abrirte a nuevas posibilidades','Permite que aparezcan nuevos horizontes.','Expandir'],['Practicar la gratitud','Observa lo bueno que ya está presente.','Expandir'],['Compartir tu luz','Lleva tu calma a tus vínculos.','Expandir'],['Cultivar la compasión','Trátate y trata a otros con ternura.','Expandir'],['Vivir con intención','Elige cómo quieres habitar tu día.','Expandir'],['Confiar en tu proceso','Cada paso tiene su propio ritmo.','Expandir'],['Integrar tu aprendizaje','Reúne lo que has descubierto.','Expandir'],['Celebrar tu transformación interior','Reconoce la persona que estás cultivando.','Expandir'],['Continuar brillando','Tu práctica puede seguir acompañándote.','Expandir'],
].map(([title, description, stage], index) => ({ day: index + 1, title, description, stage, audio: `/audios/dia-${String(index + 1).padStart(2, '0')}.mp3` }))

const stages = ['Todos', 'Despertar', 'Liberar', 'Fortalecer', 'Expandir']

export default function Page() {
  const [view, setView] = useState<'landing' | 'access' | 'app'>('landing')
  const [appTab, setAppTab] = useState<'inicio' | 'biblioteca' | 'diario' | 'calendario'>('inicio')
  const [selectedStage, setSelectedStage] = useState('Todos')
  const [selected, setSelected] = useState<Meditation | null>(null)
  const [completed, setCompleted] = useState<number[]>([1, 2, 3, 4, 5])
  const [playing, setPlaying] = useState(false)
  const [reflection, setReflection] = useState('')
  const [savedReflection, setSavedReflection] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)

  const filtered = useMemo(() => selectedStage === 'Todos' ? meditationData : meditationData.filter((item) => item.stage === selectedStage), [selectedStage])
  const progress = Math.round((completed.length / 30) * 100)
  const continueMeditation = meditationData.find((item) => !completed.includes(item.day)) ?? meditationData[29]

  function begin() { setView('access') }
  function enter() { setView('app') }
  function markComplete() { if (selected && !completed.includes(selected.day)) setCompleted((current) => [...current, selected.day]); setPlaying(false) }

  if (view === 'landing') return <Landing onBegin={begin} />
  if (view === 'access') return <Access onEnter={enter} />

  return <main className="app-frame">
    <header className="app-header"><button className="brand" onClick={() => setAppTab('inicio')}><span className="brand-orbit"><Moon /></span><span>FRECUENCIA <b>DIVINA 7</b></span></button><nav className={menuOpen ? 'mobile-nav open' : 'mobile-nav'}>{[['inicio','Mi espacio'],['biblioteca','Meditaciones'],['diario','Diario'],['calendario','Calendario']].map(([id, label]) => <button key={id} className={appTab === id ? 'active' : ''} onClick={() => { setAppTab(id as typeof appTab); setMenuOpen(false) }}>{label}</button>)}</nav><div className="header-actions"><span className="progress-mini"><span style={{ width: `${progress}%` }} /></span><span>{progress}%</span><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X /> : <Menu />}</button><button className="avatar">L</button></div></header>
    <div className="app-content">
      {appTab === 'inicio' && <Dashboard progress={progress} continueMeditation={continueMeditation} completed={completed} onContinue={() => { setSelected(continueMeditation); setPlaying(false) }} onLibrary={() => setAppTab('biblioteca')} />}
      {appTab === 'biblioteca' && <section className="section-page"><PageIntro eyebrow="TU RECORRIDO" title="Biblioteca de meditaciones" description="Treinta prácticas de siete minutos para acompañarte, un día a la vez." /><div className="stage-tabs">{stages.map((stage) => <button className={selectedStage === stage ? 'selected' : ''} key={stage} onClick={() => setSelectedStage(stage)}>{stage}</button>)}</div><div className="meditation-grid">{filtered.map((item) => <MeditationCard key={item.day} item={item} done={completed.includes(item.day)} onSelect={() => { setSelected(item); setPlaying(false) }} />)}</div></section>}
      {appTab === 'diario' && <section className="section-page narrow"><PageIntro eyebrow="TU ESPACIO ÍNTIMO" title="Diario espiritual" description="Escribe unas palabras para integrar lo que despierta en ti cada práctica." /><div className="journal-card"><div className="journal-prompt"><Sparkles /><span>Reflexión del día {continueMeditation.day}</span></div><h2>¿Cómo me siento hoy?</h2><textarea value={reflection} onChange={(event) => { setReflection(event.target.value); setSavedReflection(false) }} placeholder="Escribe aquí lo que quieras guardar para ti..." /><div className="journal-footer"><span>{new Date().toLocaleDateString('es-MX', { day: 'numeric', month: 'long', year: 'numeric' })}</span><button className="gold-button" onClick={() => setSavedReflection(true)}>Guardar reflexión</button></div>{savedReflection && <p className="saved-note"><Check /> Tu reflexión quedó guardada en esta sesión.</p>}</div></section>}
      {appTab === 'calendario' && <section className="section-page"><PageIntro eyebrow="TU CONSTANCIA" title="Calendario de 30 días" description="Cada marca representa un momento que elegiste regalarte." /><div className="calendar-card"><div className="calendar-legend"><span><i className="done-dot" /> Completado</span><span><i className="available-dot" /> Disponible</span><span><i className="pending-dot" /> Pendiente</span></div><div className="calendar-grid">{meditationData.map((item) => <button key={item.day} className={completed.includes(item.day) ? 'calendar-day done' : item.day === continueMeditation.day ? 'calendar-day available' : 'calendar-day'} onClick={() => { setSelected(item); setPlaying(false) }}><span>{item.day}</span>{completed.includes(item.day) && <Check />}</button>)}</div></div></section>}
    </div>
    {selected && <AudioPlayer item={selected} playing={playing} setPlaying={setPlaying} onClose={() => setSelected(null)} onComplete={markComplete} />}
  </main>
}

function Landing({ onBegin }: { onBegin: () => void }) { return <main className="landing"><header className="landing-nav"><button className="brand" onClick={onBegin}><span className="brand-orbit"><Moon /></span><span>FRECUENCIA <b>DIVINA 7</b></span></button><button className="nav-access" onClick={onBegin}>Ingresar <ArrowRight /></button></header><section className="hero"><div className="hero-copy"><p className="eyebrow"><Star /> UNA PRÁCTICA PARA VOLVER A TI</p><h1>Siete minutos para <em>silenciar</em> el ruido y reencontrar tu luz.</h1><p className="hero-lead">Treinta días para cultivar calma, presencia y conexión con tu luz interior.</p><p className="hero-text">Regálate siete minutos al día. Un espacio de serenidad creado para respirar, soltar el ruido y volver a conectar contigo.</p><button className="gold-button large" onClick={onBegin}>Comenzar mi experiencia <ArrowRight /></button><p className="microcopy">Una invitación al bienestar, sin prisa y sin perfección.</p></div><div className="celestial-art"><div className="halo halo-one" /><div className="halo halo-two" /><div className="moon-art"><Moon /></div><div className="star-field">{Array.from({ length: 18 }, (_, index) => <i key={index} style={{ '--i': index } as React.CSSProperties} />)}</div><div className="art-caption"><span>30 DÍAS</span><b>DE PRESENCIA</b></div></div></section><section className="intro-section"><div><p className="eyebrow">EL MÉTODO</p><h2>Un ritual pequeño puede cambiar la forma en que habitas tu día.</h2></div><div className="intro-text"><p>Frecuencia Divina 7 es una experiencia guiada de atención plena para hacer una pausa, escuchar tu mundo interior y construir una práctica amable.</p><div className="steps"><div><b>01</b><span>Respira</span></div><div><b>02</b><span>Escucha</span></div><div><b>03</b><span>Integra</span></div></div></div></section><section className="stages-section"><p className="eyebrow">EL RECORRIDO</p><h2>Cuatro etapas. Un espacio para ti.</h2><div className="stage-cards">{[['01','Despertar','Volver al presente con curiosidad.'],['02','Liberar','Soltar con suavidad lo que pesa.'],['03','Fortalecer','Cultivar confianza y serenidad.'],['04','Expandir','Llevar tu luz a lo cotidiano.']].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><footer><span>FRECUENCIA DIVINA 7</span><span>Una práctica de bienestar y conexión interior.</span></footer></main> }

function Access({ onEnter }: { onEnter: () => void }) { return <main className="access-page"><div className="access-decoration"><Moon /></div><section className="access-card"><button className="brand centered" onClick={onEnter}><span className="brand-orbit"><Moon /></span><span>FRECUENCIA <b>DIVINA 7</b></span></button><p className="eyebrow">TU ESPACIO DE LUZ</p><h1>Bienvenida de vuelta.</h1><p className="access-copy">Entra para continuar tu práctica diaria.</p><label>Correo electrónico<input type="email" placeholder="tu@correo.com" /></label><label>Contraseña<input type="password" placeholder="••••••••" /></label><button className="gold-button full" onClick={onEnter}>Ingresar <ArrowRight /></button><button className="text-link" onClick={onEnter}>Crear mi cuenta</button><div className="demo-note"><LockKeyhole /> Vista de demostración: la autenticación real se conectará cuando agregues tu proveedor.</div></section></main> }

function Dashboard({ progress, continueMeditation, completed, onContinue, onLibrary }: { progress: number; continueMeditation: Meditation; completed: number[]; onContinue: () => void; onLibrary: () => void }) { return <section className="dashboard"><div className="welcome-row"><div><p className="eyebrow">BUENOS DÍAS, LUZ</p><h1>Bienvenida a tu espacio de luz.</h1><p>Hoy solo necesitas siete minutos para volver a ti.</p></div><div className="date-pill"><Moon /> <span>{new Date().toLocaleDateString('es-MX', { weekday: 'long', day: 'numeric', month: 'long' })}</span></div></div><div className="dashboard-grid"><div className="progress-card"><div className="card-top"><div><p className="eyebrow">TU RECORRIDO</p><h2>Día {continueMeditation.day} de 30</h2></div><div className="progress-ring"><strong>{progress}%</strong><span>completado</span></div></div><div className="big-progress"><span style={{ width: `${progress}%` }} /></div><div className="progress-meta"><span>{completed.length} prácticas completadas</span><span>30 días</span></div><button className="gold-button" onClick={onContinue}>Continuar mi camino <ArrowRight /></button></div><div className="quote-card"><Sparkles /><p>“La calma no es un lugar al que llegas. Es una forma de caminar.”</p><span>— Tu intención de hoy</span></div></div><div className="dashboard-lower"><div className="next-card"><div className="section-label"><span>PRÓXIMA MEDITACIÓN</span><button onClick={onLibrary}>Ver biblioteca <ArrowRight /></button></div><div className="next-content"><div className="day-number">{String(continueMeditation.day).padStart(2, '0')}</div><div><h2>{continueMeditation.title}</h2><p>{continueMeditation.description}</p><span className="duration"><Clock3 /> 7 minutos · {continueMeditation.stage}</span></div><button className="play-button" onClick={onContinue}><CirclePlay /></button></div></div><div className="mini-card"><BookOpen /><h3>Tu diario</h3><p>¿Qué quieres agradecer hoy?</p></div></div></section> }

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div> }
function MeditationCard({ item, done, onSelect }: { item: Meditation; done: boolean; onSelect: () => void }) { return <article className={done ? 'meditation-card completed' : 'meditation-card'}><div className="meditation-number">{String(item.day).padStart(2, '0')}</div><div className="meditation-info"><span className="stage-tag">{item.stage}</span><h2>{item.title}</h2><p>{item.description}</p><span className="duration"><Clock3 /> 7 minutos</span></div><button className="card-action" onClick={onSelect}>{done ? <><Check /> Completada</> : <><Play /> Escuchar</>}</button></article> }
function AudioPlayer({ item, playing, setPlaying, onClose, onComplete }: { item: Meditation; playing: boolean; setPlaying: (value: boolean) => void; onClose: () => void; onComplete: () => void }) { return <aside className="audio-player"><div className="audio-art"><Moon /></div><div className="audio-details"><span>AHORA EN TU ESPACIO</span><h2>Día {item.day}: {item.title}</h2><p>Esta meditación estará disponible próximamente.</p><div className="audio-progress"><span /></div><div className="audio-times"><span>00:00</span><span>07:00</span></div></div><div className="audio-controls"><button aria-label="Volumen"><Volume2 /></button><button className="main-play" onClick={() => setPlaying(!playing)}>{playing ? <Pause /> : <Play />}</button><button onClick={onComplete} className="complete-audio"><Check /> Marcar como completada</button><button onClick={onClose} aria-label="Cerrar reproductor"><X /></button></div></aside> }
